/* INSERT PLAYERS INTO BOOKMARKS */
INSERT INTO Bookmarks (pid, uid) VALUES (1, 2);

/* GET BOOKMARK ENTRY FOR USER */
SELECT * FROM Bookmarks WHERE pid = 1 AND uid = 2;

/* GET ALL PLAYERS FROM BOOKMARKS */
SELECT * FROM Bookmarks NATURAL JOIN Player WHERE uid = 1 LIMIT 10 OFFSET 0 * 10;

/* DELETE PLAYERS FROM BOOKMARKS */
DELETE FROM Bookmarks WHERE pid = 1 AND uid = 2;
