-- Enum for types of user roles
CREATE TYPE roleType AS ENUM ('admin', 'user');

CREATE TABLE HUser (
	uid int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	hash text,
	email text UNIQUE NOT NULL,
	uName text,
	uRole roleType
);

CREATE TABLE Player (
	pid int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	firstName text,
	lastName text
);

CREATE TABLE Bookmarks (
	uid int REFERENCES HUser ON UPDATE CASCADE ON DELETE CASCADE,
	pid int REFERENCES Player ON UPDATE CASCADE ON DELETE CASCADE,
	PRIMARY KEY (uid, pid)
);

CREATE TABLE Team (
	abbrev varchar(5) NOT NULL PRIMARY KEY,
	tName text
);

CREATE TABLE TeamStats (
	abbrev varchar(5) NOT NULL REFERENCES Team ON UPDATE CASCADE ON DELETE CASCADE,
	wins int,
	losses int,
	season int NOT NULL,
	PRIMARY KEY (abbrev, season)
);

CREATE TABLE PlayerStats (
	pid int NOT NULL REFERENCES Player ON UPDATE CASCADE ON DELETE CASCADE,
	assists int, 
	rebounds int,
	points int,
	games int,
	season int NOT NULL,
	abbrev varchar(5) NOT NULL REFERENCES Team ON UPDATE CASCADE ON DELETE CASCADE,
	PRIMARY KEY (pid, season, abbrev)
);
